#!/bin/sh

# Install dots
dot_inst()
{
  echo "dots" >> .gitignore
  git clone --bare https://github.com/hoaxdream/dots.git $HOME/.config/dots
  git --git-dir=$HOME/.config/dots/ --work-tree=$HOME checkout
  git --git-dir=$HOME/.config/dots/ --work-tree=$HOME config --local status.showUntrackedFiles no
}

# Clone repos
repo_inst()
{
  git clone https://git.suckless.org/dwm ~/.config/dwm
  git clone https://git.suckless.org/st ~/.config/st
  git clone https://git.suckless.org/dmenu ~/.config/dmenu
  git clone https://github.com/jarun/nnn ~/.config/nnn
  git clone https://github.com/hoaxdream/startpage ~/.config/startpage
}

# Cleanup
clean_inst()
{
  mkdir ~/.config/dl
  mkdir ~/.config/dl/torrent
  mkdir ~/.config/dl/torrent/fin
  mkdir ~/.config/dl/torrent/pending
  rm ~/.bash_logout
  rm ~/.bash_profile
  rm ~/.bashrc
  rm ~/.zshrc
}

echo 'dotfiles'
dot_inst
echo 'repos'
repo_inst
echo 'clean'
clean_inst
