#!/bin/sh
# https://github.com/hoaxdream
# author: hoaxdream

# install dots
inst_dot()
  {
    cd ~
    rm ~/.config/user-dirs.dirs
    echo "dots" >> .gitignore
    git clone --bare https://github.com/hoaxdream/dots.git $HOME/.config/dots
    git --git-dir=$HOME/.config/dots/ --work-tree=$HOME checkout
    git --git-dir=$HOME/.config/dots/ --work-tree=$HOME config --local status.showUntrackedFiles no
  }
# dwm,st,dmenu,startpage
inst_repo()
  {
    # clone the repositories
    git clone https://github.com/hoaxdream/dwm ~/.config/dwm
    git clone https://github.com/hoaxdream/st ~/.config/st
    git clone https://github.com/hoaxdream/dmenu ~/.config/dmenu
    git clone https://github.com/hoaxdream/startpage ~/.config/startpage
    git clone https://github.com/jarun/nnn ~/.config/nnn
    # make install
    cd ~/.config/dwm
    make && sudo make install
    cd ~/.config/st
    make && sudo make install
    cd ~/.config/dmenu
    make && sudo make install
  }
# make directories
inst_mkd()
  {
    mkdir ~/.config/dl
    mkdir ~/.config/dl/torrent
    mkdir ~/.config/dl/torrent/fin
    mkdir ~/.config/dl/torrent/pending
  }

echo 'dotfiles'
inst_dot
echo 'repositories'
inst_repo
echo 'clean'
inst_mkd

echo 'Run sudo ./partcore then sudo ./partdata for fresh disk, otherwise just run sudo ./postinstall then reboot'
