#!/bin/sh
# https://github.com/hoaxdream
# author: hoaxdream

# cp and mv progress
int_coreutil()
  {
    cd ~/.config/work
    wget http://ftp.gnu.org/gnu/coreutils/coreutils-9.0.tar.xz
    tar xvJf coreutils-9.0.tar.xz
    cd coreutils-9.0/
    wget https://raw.githubusercontent.com/jarun/advcpmv/master/advcpmv-0.9-9.0.patch
    patch -p1 -i advcpmv-0.9-9.0.patch
    ./configure
    make
    sudo mv ./src/cp /usr/local/bin/cpg
    sudo mv ./src/mv /usr/local/bin/mvg
  }
# nnn
int_nnn()
  {
    cd ~/.config/nnn
    make O_NERD=1 && sudo make install
  }
# fix alias
int_fixalias()
  {
    sed -i 's/cp="cp"/cp="cpg -g"/g' ~/.config/zsh/aliasrc
    sed -i 's/mv="mv"/mv="mvg -g"/g' ~/.config/zsh/aliasrc
  }
# mpd user daemon
int_mpd()
  {
    systemctl --user enable mpd
  }
# cron
int_cron()
  {
    mkdir ~/.config/cron
    cp ~/.config/work/backups/cronsaved ~/.config/cron/cronsaved
  }

echo 'cp and mv progress'
int_coreutil
echo 'nnn file manager'
int_nnn
echo 'fix alias'
int_fixalias
echo 'mpd'
int_mpd
echo 'cron'
int_cron
