#!/bin/bash
# https://github.com/hoaxdream
# author: hoaxdream

# arch aur helper yay
install_aur()
  {
    cd /tmp/
    curl -LO https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz
    tar xvzf yay.tar.gz
    cd  yay
    makepkg -sci
  }
# dot manage with git bare
install_dots()
  {
    cd ~
    mkdir ~/.config
    chmod 700 ~/.config
    git clone --bare https://github.com/jeremy/dots.git $HOME/.config/dots
    git --git-dir=$HOME/.config/dots/ --work-tree=$HOME checkout
    git --git-dir=$HOME/.config/dots/ --work-tree=$HOME config --local status.showUntrackedFiles no
  }
# clone needed repos
install_repos()
  {
    git clone https://git.suckless.org/dwm ~/.config/dwm
    cd ~/.config/dwm
    make
    cd ~
    git clone https://git.suckless.org/st ~/.config/st
    cd ~/.config/st
    make
    cd ~
    git clone https://git.suckless.org/dmenu ~/.config/dmenu
    cd ~/.config/dmenu
    make
    cd ~
    git clone https://github.com/jarun/nnn ~/.config/nnn
    cd ~/.config/nnn
    make O_NERD=1
    cd ~
    git clone https://github.com/hoaxdream/startpage ~/.config/startpage
  }
# arch packages installation
install_pkgs()
  {
    # xorg
    pkgs="xorg-server xorg-xwininfo xorg-xprop xorg-xdpyinfo"
    pkgs="$pkgs xorg-xset xorg-xsetroot xorg-xinit xterm"
    # nvidia
    pkgs="$pkgs nvidia nvidia-utils lib32-nvidia-utils nvidia-settings"
    pkgs="$pkgs vulkan-icd-loader lib32-vulkan-icd-loader"
    # core
    pkgs="$pkgs xcape mlocate man-db wget zip unzip unrar dosfstools ntfs-3g"
    pkgs="$pkgs xdg-user-dirs xclip xdo xdotool mediainfo transmission-cli bc tree"
    # audio
    pkgs="$pkgs pulseaudio-alsa pulsemixer pamixer"
    # fonts
    pkgs="$pkgs ttf-joypixels ttf-dejavu ttf-nerd-fonts-symbols"
    pkgs="$pkgs noto-fonts noto-fonts-emoji ttf-liberation"
    # others
    pkgs="$pkgs youtube-dl ffmpeg maim sxiv xwallpaper imagemagick"
    pkgs="$pkgs newsboat picom mpd mpc mpv ncmpcpp easytag"
    pkgs="$pkgs zathura zathura-pdf-mupdf poppler"
    pkgs="$pkgs dunst libnotify gucharmap"
    pkgs="$pkgs firefox steam gimp htop transmission-cli"
    # aur packages
    pkgs="$pkgs tremc"
    # emoji libxft-bgra
    yay --needed --noconfirm -Syu $pkgs
    yes | yay -S libxft-bgra-git
    # user daemons
    touch ~/.config/mpd/playlists
    systemctl --user enable mpd
  }
# cleanup
clean_up()
  {
    rm ~/.bash_logout
    rm ~/.bash_profile
    rm ~/.bashrc
    rm ~/.zshrc
  }

echo 'yay aur helper'
install_aur
echo 'git bare dotfiles'
install_dots
echo 'clone repos'
install_repos
echo 'install pkgs'
install_pkgs
echo 'cleanup'
clean_up
echo 'Run sudo ./postinstall then reboot.'
