#!/bin/sh
# https://github.com/hoaxdream
# author: hoaxdream

# arch aur helper yay
inst_aur()
  {
    cd /tmp/
    curl -LO https://aur.archlinux.org/cgit/aur.git/snapshot/yay.tar.gz
    tar xvzf yay.tar.gz
    cd  yay
    makepkg -sci
  }
# arch packages installation
inst_pkgs()
  {
    # xorg
    pkgs="xorg-server xorg-xwininfo xorg-xprop xorg-xdpyinfo"
    pkgs="$pkgs xorg-xset xorg-xsetroot xorg-xinit xterm"
    # nvidia
    pkgs="$pkgs nvidia nvidia-utils lib32-nvidia-utils nvidia-settings"
    pkgs="$pkgs vulkan-icd-loader lib32-vulkan-icd-loader"
    # core
    pkgs="$pkgs xcape mlocate man-db wget zip unzip unrar dosfstools ntfs-3g"
    pkgs="$pkgs xdg-user-dirs xclip xdo xdotool mediainfo transmission-cli bc tree"
    # audio
    pkgs="$pkgs pulseaudio-alsa pulsemixer pamixer"
    # fonts
    pkgs="$pkgs ttf-joypixels ttf-dejavu ttf-nerd-fonts-symbols ttf-roboto-mono"
    pkgs="$pkgs noto-fonts noto-fonts-emoji ttf-liberation ttf-ibm-plex"
    # others
    pkgs="$pkgs youtube-dl ffmpeg maim sxiv xwallpaper imagemagick"
    pkgs="$pkgs newsboat picom mpd mpc mpv ncmpcpp"
    pkgs="$pkgs zathura zathura-pdf-mupdf poppler python-adblock cronie"
    pkgs="$pkgs dunst libnotify gucharmap htop discord"
    pkgs="$pkgs qutebrowser steam signal-desktop transmission-cli"
    daemon="cronie"
    # aur packages
    pkgs="$pkgs tremc"
    # emoji libxft-bgra
    yay --needed --noconfirm -Syu $pkgs
    yes | yay -S libxft-bgra-git
    # system daemon
    systemctl enable $daemon
  }

echo 'yay aur helper'
inst_aur
echo 'install packages'
inst_pkgs

echo 'Packages installation completed please reboot'
